fixing bunch of formatting warnings
accel-sim/gpgpu-sim_distribution pull request #53
Opened 2023-06-06 19:36 UTC by LAhmos

fixed most of the formatting related warnings

2023-06-09 19:08 UTC, FJShen requested changes

2023-06-09 19:08 UTC, FJShen commented on src/cuda-sim/instructions.cc
> +      fprintf(fp, "%s %u %s %d\n", name.c_str(), it->second, dec.c_str(),
Are we certain `it->second` always holds a variable no larger than `unsigned` in this context? If yes, this fix is justifiable. If no, the fix will cause any variable the union is holding - longer than type `unsigned` - to be stripped of higher order bits in the printout.

2023-06-09 19:08 UTC, FJShen commented on src/cuda-sim/ptx_sim.cc
> +      fprintf(fp, ".f16 %f [0x%04x]\n", static_cast<float>(value.f16), (unsigned)value.u16);
Please use method `half::operator float()` to do the conversion.

2023-06-09 19:14 UTC, FJShen commented on src/cuda-sim/ptx_sim.cc
> +      fprintf(fp, ".f16 %f [0x%04x]\n", static_cast<float>(value.f16), (unsigned)value.u16);
Please disregard the above comment. Your code is correct, static_cast will call the overloaded float typecast of `half`.

2023-06-09 19:48 UTC, FJShen commented on src/cuda-sim/instructions.cc
> +      fprintf(fp, "%s %u %s %d\n", name.c_str(), it->second, dec.c_str(),
Actually if `it->second` is a union, the correct way to access its contents is to specify a member name, e.g. `it->second.u16`

2023-06-10 00:44 UTC, LAhmos commented on src/cuda-sim/instructions.cc
> +      fprintf(fp, "%s %u %s %d\n", name.c_str(), it->second, dec.c_str(),
I agree, I am not sure what happens when we access a union without specifying the member.

2023-06-10 00:44 UTC, LAhmos commented on src/cuda-sim/instructions.cc
> +      fprintf(fp, "%s %u %s %d\n", name.c_str(), it->second, dec.c_str(),
I didn't mean to push this as a fix, we still have the warning anyway

2023-06-12 16:54 UTC, FJShen approved these changes

2023-06-12 21:30 UTC, FJShen commented
Looks good. 

However `void ptx_thread_info::print_reg_thread(char *fname)` needs to be improved to correctly print the intended contents of `union ptx_reg_t`. Maybe open a new issue to keep track of this bug?

2023-06-12 21:31 UTC, merged