137 drop sector cache flexibility
accel-sim/gpgpu-sim_distribution pull request #57
Opened 2023-06-12 20:19 UTC by FJShen

Fix for issue https://github.com/accel-sim/accel-sim-framework/issues/137

2023-06-12 20:22 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.h
> -        sscanf(config, "%c:%u:%u:%u,%c:%c:%c:%c:%c,%c:%u:%u,%u:%u,%u", &ct,
Just reformatting the newlines, so that each cluster of params surrounded by commas are in one line

2023-06-14 03:17 UTC, JRPan commented
Looks good. There is a new config introduced by https://github.com/accel-sim/gpgpu-sim_distribution/pull/54. I just merged it. Could you please also update the new GV100 config with the changes?

2023-06-14 03:17 UTC, JRPan requested changes
Update GV100 config introduced by https://github.com/accel-sim/gpgpu-sim_distribution/pull/54

2023-06-17 00:39 UTC, JRPan approved these changes

2023-06-17 23:03 UTC, merged