LDGSTS, LDGDEPBAR and DEPBAR Implementations
accel-sim/gpgpu-sim_distribution pull request #62
Opened 2023-09-18 20:18 UTC by Connie120

This PR includes the LDGSTS, LDGDEPBAR and DEPBAR implementations that's specifically for the NVIDIA Ampere architecture.

2023-09-18 20:38 UTC, FJShen commented
Please add comments to your code citing the specification of, or an explanation for, what these instructions are supposed to do.

2023-09-18 21:07 UTC, JRPan commented
It's probably better to assign the same guy the review the frontend and the backend

2023-09-19 02:32 UTC, FJShen commented on src/gpgpu-sim/shader.h
> +#define WID 2
Get rid of all ad-hoc personal debugging code using these numbers

2023-09-19 02:36 UTC, FJShen commented on src/gpgpu-sim/shader.h
> +    // warp_inst_t *m_warp;
Is it necessary to turn m_warp from private to public?

2023-09-19 02:39 UTC, FJShen commented on src/gpgpu-sim/shader.cc
> +  // display_simt_state(fout, mask);
Why comment out this line?

2023-09-19 03:07 UTC, FJShen commented on src/gpgpu-sim/shader.h
> +      m_pending_ldgsts;
Nice documentation for the meaning of each level of key. However you can further
improve the comments to make it compatible with common documentation tools, such
that the meanings of each key can show up in VS Code intellisense (hover your
mouse over the variable name). Try this:

```suggestion
  /**
   * A multi-level map: unsigned (warp_id) -> unsigned (pc) -> unsigned (addr) -> unsigned (count)
   */
  std::map<unsigned /*warp_id*/,
           std::map<unsigned /*pc*/, 
                  std::map<unsigned /*addr*/, unsigned /*count*/>>>
      m_pending_ldgsts;
```

2023-09-19 03:11 UTC, FJShen requested changes
Please address my comments

2023-09-19 17:10 UTC, FJShen approved these changes

2023-09-20 18:53 UTC, merged

2024-05-23 05:49 UTC, YWHyuk commented
Hi @Connie120, I'm simulating Ampere architecture using your #62 features.

When I run the simulator, a deadlock occurs. Upon investigating the details, it seems that the warps' `m_waiting_ldgsts` is set to 1, and there is no place where `m_waiting_ldgsts` is reset to 0, causing the deadlock.

Also, I reviewed your PR and I'm curious where the part that increases the counter of `m_pending_ldgsts` is located.

2024-05-23 17:40 UTC, Connie120 commented
@YWHyuk Please check the unset_depbar function in shader.cc: https://github.com/accel-sim/gpgpu-sim_distribution/blob/7dc9977199f6a79f58191b18b64568b6155873ac/src/gpgpu-sim/shader.cc#L1849, which sets m_waiting_ldgsts to false. It's called at several places, and you can find it in shader.cc. 

For m_pending_ldgsts, please try to add the following line **within the outer if statement** after https://github.com/accel-sim/gpgpu-sim_distribution/blob/7dc9977199f6a79f58191b18b64568b6155873ac/src/gpgpu-sim/shader.cc#L2644
```
if (inst->m_is_ldgsts) {
      m_pending_ldgsts[warp_id][inst->pc][inst->get_addr(0)] += n_accesses;
}
```
I think I accidentally deleted this, thanks for bringing it up. Adding these lines could be a quick fix. Also, please let me know what app you are using so I can also test it on my end. In the meantime, if it works for you, feel free to create a PR. Or if it still doesn't work, let me know, I'll try to fix it.

2024-05-24 17:02 UTC, YWHyuk commented
Thank you @Connie120  for quick response :)

I applied the method you mentioned, and with one additional minor fix, **it works now!**

I have attached the trace of my application. This application is CUTLASS's GEMM kernel using Tensor Cores of the Ampere architecture, and the size is 256x256x256 (MxNxK).

[gemm_256.zip](https://github.com/accel-sim/gpgpu-sim_distribution/files/15437685/gemm_256.zip)

I used the SM86_RTX3070 configuration, and setting `-gpgpu_n_clusters` to 1 reproduces the situation where the deadlock occurs.

The minor fix I made is an exception handling for the following situation.
```
2050 ffffffff 1 R72 LDSM.16.M88.4 1 R66 2 2 0x6000 32 32 32 432 32 32 32 432 -32 96 -32 496 -32 96 -32 432 32 32 32 432 32 32 32 432 -32 96 -32 496 -32 96 -32 0 
2060 ffffffff 1 R76 LDSM.16.M88.4 1 R66 2 2 0x7000 32 32 32 432 32 32 32 432 -32 96 -32 496 -32 96 -32 432 32 32 32 432 32 32 32 432 -32 96 -32 496 -32 96 -32 0 
2070 00000000 0 BRA 0 0 6352 
2080 ffffffff 0 LDGDEPBAR 0 0 0  <--------------------------- m_ldgdepbar_id++
2090 ffffffff 0 ISETP.NE.U32.AND 1 R255 0 0                   No ldgsts instruction between LDGDEPBARs
20a0 ffffffff 0 LDGDEPBAR 0 0 0  <--------------------------- m_ldgdepbar_id++
20b0 ffffffff 0 ISETP.NE.AND.EX 1 R255 0 0 
20c0 ffffffff 0 DEPBAR.LE 0 0 0 
20d0 ffffffff 0 BAR.SYNC.DEFER_BLOCKING 0 0 0 
```

I'll send these fixes as a PR.

2024-05-24 18:01 UTC, Connie120 commented
@YWHyuk Glad it works! Please add me as the reviewer of your PR so I can take a look, thanks!