Stream stats
accel-sim/gpgpu-sim_distribution pull request #71
Opened 2024-05-14 03:54 UTC by JRPan

Collect stats based on streams. 

99% Ready. Creating a PR to trigger GitHub Actions to generate correlations. 

Consult @JRPan before merging.

2024-05-14 04:28 UTC, mattsinc commented
@JRPan let me know if you need something from UW here

2024-06-22 21:58 UTC, mattsinc commented
@JRPan just checking again if you need anything from us?

2024-08-09 22:22 UTC, JRPan commented
Sorry for the delay, this will be included in the next major release. https://github.com/accel-sim/accel-sim-framework/issues/317

2024-08-13 20:15 UTC, JRPan commented
@FJShen Lets try get this merged asap

2024-08-14 16:49 UTC, FJShen commented
I need some more description of this PR. E.g., What feature does it add? What bug does it fix? Does "stream" refer to CUDA stream?

2024-08-14 17:29 UTC, mattsinc commented
> I need some more description of this PR. E.g., What feature does it add? What bug does it fix? Does "stream" refer to CUDA stream?

@FJShen : @JRPan took the original commit my students submitted to Accel-Sim and packaged it into this.  Yes, "stream" means "CUDA stream".  We have a full tech report that describes the support we added: https://arxiv.org/abs/2304.11136

Ultimately, what these commits do is it adds support to Accel-Sim/GPGPU-Sim to track statistics at a per-CUDA stream level.

2024-08-14 18:32 UTC, JRPan commented
Thank you, Matt!

@FJShen 
Basically, an extra dimension is added for all stats. Before, all stats are collected and aggregated. In this commit, stats are collected on a per-stream basis. Within each stream, stats are aggregated just like before. If there is only 1 stream, this should behave exactly as before. In multi-stream and concurrent enabled, the old stats model does not make sense because the kernels are running concurrently and the stats cannot be separated between the kernels. This is to address that. I needed this in my paper as well. Justin's (Shichen) version here is more robust and better than mine.

For each kernel, a stream id is always given (0 by default). The stats container is usually a `std::map<stream_id, stat>`. At the end of the kernel, `print_stat` prints the stat based on the stream id. 

This mainly affects cache stats (L1 and L2), and cycles. Other stats like occupancy, DRAM, and IPC are not changed. These stats does not make sense to be separated. 

I correlated GPU ubench and rodinia. Functionally, this is correct. I assigned you as the reviewer to check more about the C++ side of this :)
Christin used this for his work as well. I worked with him and validated everything. 

I did not correlate this with any workload that runs with concurrent enabled, tho. Maybe we should write a ubench.

2024-08-14 21:19 UTC, mattsinc commented
> Thank you, Matt!
> 
> @FJShen Basically, an extra dimension is added for all stats. Before, all stats are collected and aggregated. In this commit, stats are collected on a per-stream basis. Within each stream, stats are aggregated just like before. If there is only 1 stream, this should behave exactly as before. In multi-stream and concurrent enabled, the old stats model does not make sense because the kernels are running concurrently. The stats cannot be separated between the kernels. This is to address that. I needed this in my paper as well. Justin's (Shichen) version here is more robust and better than mine.
> 
> For each kernel, a stream id is always given (0 by default). The stats container is usually a `std::map<stream_id, stat>`. At the end of the kernel, `print_stat` prints the stat based on the stream id.
> 
> This mainly affects cache stats (L1 and L2), and cycles. Other stats like occupancy, DRAM, and IPC are not changed. These stats does not make sense to be separated.
> 
> I correlated GPU ubench and rodinia. Functionally, this is correct. I assigned you as the reviewer to check more about the C++ side of this :) Christin used this for his work as well. I worked with him and validated everything.
> 
> I did not correlate this with any workload that runs with concurrent enabled, tho. Maybe we should write a ubench.

I believe we did correlate with concurrent streams in the report I linked, FWIW.

2024-08-15 04:08 UTC, FJShen commented on configs/tested-cfgs/SM7_TITANV/gpgpusim.config
This argument is set to 0 by default in gpu-sim.cc:638. I suggest duplicating this line to all other config files as well so as to remind any user of the simulator that per-stream stat is an option

2024-08-15 05:11 UTC, FJShen commented
I found some possibly erroneous code (and sub-optimal coding practice). Please kindly address the reviews above.

2024-08-15 18:20 UTC, JRPan commented
I only see one comment related to the config file. Is this correct?

2024-08-15 20:27 UTC, FJShen requested changes

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-sim.cc
> +        kernelID, kernel_time));  ///// need fix
What needs fix? Please either apply the fix, or delete this comment.

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.h
> +  std::map<unsigned long long, std::vector<std::vector<unsigned long long>>>
Please add a comment here to describe the map: what does the key represent? What does the value represent?

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.h
> +  std::map<unsigned long long, std::vector<std::vector<unsigned long long>>>
Same here. Please describe what the keys and values are, respectively.

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = cs.m_stats_pw.begin(); iter != cs.m_stats_pw.end(); ++iter) {
Is there a reason why `m_stats_pw` is handled in `operator+=()`, but omitted in `operator+()` (line 777)?

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
>    /// Print out each non-zero cache statistic for every memory access type and
Please mention `streamID` in this documentation comment.

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +    if ((streamID != -1) && (streamid != streamID)) continue;
If you want this method to print stats from all streams when "streamID is not specified", then you should go to gpu-cache.h and specify a default value (-1) for `streamID` in the declaration of this method so other programmers can understand what the default value is.

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +    // when streamID is specified, skip stats for all other streams, otherwise,
Go to the method declaration in gpu-cache.h and specify -1 to be the default value for argument `streamID`

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = m_stats.begin(); iter != m_stats.end(); ++iter) {
Should `iter` be iterating over `m_stats` or `m_stats_pw`??!

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +        m_gpu->aggregated_l1_stats.select_stats_status(status, cache_status));
Looks fishy to me. `aggregated_l1_stats` or `aggregated_l2_stats`??!

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +        m_gpu->aggregated_l1_stats.select_stats_status(status, cache_status));
l1 or l2??!

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +        m_gpu->aggregated_l1_stats.select_stats_status(status, cache_status));
l1 or l2??!

2024-08-15 20:27 UTC, FJShen commented on src/gpgpu-sim/mem_fetch.h
> +  mem_fetch(const mem_access_t &access, unsigned long long streamID,
This new constructor looks dangerous to me. Its function signature is nearly identical with the old ctor (constructor) except the second argument; their implementation are also nearly the same. This can cause trouble in several ways. (1) Some one adding code to one of the ctors can forget to apply the same change to the other ctor. (2) The C++ compiler might implicitly convert an `unsigned long long` to a `const warp_inst_t *` or vice versa because the conversion between the two types isn't non-trivial. I would suggest just sticking to the old ctor but add an additional argument for `streamID`.

2024-08-15 20:27 UTC, FJShen commented on src/stream_manager.cc
> +  finished_streams.clear();
This line is unnecessary

2024-08-15 20:28 UTC, JRPan commented on configs/tested-cfgs/SM7_TITANV/gpgpusim.config
Removed. Technically per-stream stat is always-on. The config line is just controlling whether concurrent kernel execution is enabled. It's just that per-stream stats only matters if there is concurrent execution but funtionally these are two different features.

2024-08-15 20:29 UTC, JRPan commented on src/gpgpu-sim/gpu-cache.cc
> +        m_gpu->aggregated_l1_stats.select_stats_status(status, cache_status));
Nice catch.

2024-08-15 20:30 UTC, FJShen commented
@JRPan I forgot to "submit" the reviews. I hope they are now visible.

2024-08-15 20:40 UTC, JRPan commented on src/gpgpu-sim/gpu-cache.cc
> +    if ((streamID != -1) && (streamid != streamID)) continue;
I actually removed default value on purpose. Every kernel should have a streamID. If no stream is specificed in CUDA, it should be 0. The -1 should be used like power_stat.cc#L186: `core_cache_stats->print_stats(fout, -1);`

2024-08-15 20:44 UTC, JRPan commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = cs.m_stats_pw.begin(); iter != cs.m_stats_pw.end(); ++iter) {
This is what original code does. Not sure if this was on purpose tho.

2024-08-17 18:29 UTC, FJShen commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = cs.m_stats_pw.begin(); iter != cs.m_stats_pw.end(); ++iter) {
I think we should make the semantics of + and += as close as possible

2024-08-19 00:37 UTC, mattsinc commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = cs.m_stats_pw.begin(); iter != cs.m_stats_pw.end(); ++iter) {
@ShichenQiao do you remember why we did += but not +?  I assume + was not used in the code we touched?

2024-08-19 00:44 UTC, JRPan commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = cs.m_stats_pw.begin(); iter != cs.m_stats_pw.end(); ++iter) {
It was not @ShichenQiao 's problem. The original code does not handle m_stats_pw in operator+. He just updated the operators to match the original functionality. 

No worries, it's a problem on our side. I'll update the operator to fix the issue.

2024-08-20 21:15 UTC, JRPan commented on src/gpgpu-sim/gpu-cache.cc
> +  for (auto iter = cs.m_stats_pw.begin(); iter != cs.m_stats_pw.end(); ++iter) {
Fixed

2024-08-21 00:23 UTC, FJShen approved these changes
Looks good to me.

2024-08-21 00:54 UTC, merged